### ISSUE TITLE
[Prioridade: 5] Listar livros de cada etiqueta

### ISSUE THREAD

**Issue by spnkdev** [DRFP/Personal-Library#16]

**Comment by DRFP** [comment]
Tarefas:
-Dar funcionalidade ao botão "Add" de forma a adicionar o livro a uma etiqueta;
-Criar evento de clique para que ao clicar numa determinada etiqueta apareça uma lista de livros adicionados a essa etiqueta;
-Testar funcionalidades;

**Comment by DRFP** [comment]
Pontos de história: 5
