### ISSUE TITLE
[Prioridade: 3] Mostrar informação sobre livro selecionado

### ISSUE THREAD

**Issue by spnkdev** [DRFP/Personal-Library#17]

**Comment by DRFP** [comment]
Tarefas:
-Criar um evento de clique para quando se selecionar um livro apareça uma interface;
-Criar Interface para apresentar informação do livro selecionado;
-Adquirir informação presente na base de dados;
-Demonstrar ao utilizador informações importantes como Autor, Editora, etc;
-Testar todos as funcionalidades.

**Comment by DRFP** [comment]
Pontos de história: 5
