### ISSUE TITLE
Sprint 2 - Goal - Capacidade

### ISSUE THREAD

**Issue by KaiZ51** [DRFP/Personal-Library#19]
Para este sprint o objetivo da aplicação será fazer a criação de funcionalidades das etiquetas.

**Comment by DRFP** [comment]
O Objetivo do Sprint 2 tem de estar resumido numa so frase. Exemplo:O Objetivo do 2º Sprint é fazer o registo de utilizador.

**Comment by DRFP** [comment]
A equipa de desenvolvimento estima que consegue completar 25 pontos de história.
