### ISSUE TITLE
[Prioridade: 3] Registar empréstimo de livro

### ISSUE THREAD

**Issue by DRFP** [DRFP/Personal-Library#7]
No caso de um cliente emprestar um determinado livro, a aplicação deve auxiliar o utilizador dando-lhe suporte para inserir essa informação.

**Comment by KaiZ51** [comment]
Deve ser possível registar o empréstimo de um ou mais livros a outra pessoa. Deverá ser possível de registar o nome da pessoa, uma data de devolução (opcionalmente), e observações opcionais acerca desse empréstimo.

**Comment by DRFP** [comment]
Business Value: 8
